# ---
#- hosts: all
#- name: Include dynamic variables 
#  tasks:
# import_playbook: ../static-assignments/common.yml 
#  include: ../dynamic-assignments/env-vars.yml
#  tags:
#    - always
    
#- hosts: all
#- import_playbook: ../static-assignments/common-del.yml

#- hosts: uat-webservers
#- name: Webserver assignments 
#  import_playbook: ../static-assignments/uat-webservers.yml


- name: import common file
  import_playbook: ../static-assignments/common.yml
  tags:
    - always

- name: include env-var file
  import_playbook: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- name: import database file
  import_playbook: ../static-assignments/db.yml

- hosts: import uat-webservers file
  import_playbook: ../static-assignments/uat-webservers.yml

- name: import loadbalancers assignment
  import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required 





